name: Semgrep + SOOS SAST Scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]

jobs:
  semgrep_scan:
    name: Semgrep Static Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.96.0
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          mkdir -p security-reports
          semgrep scan -q --sarif --config auto . > security-reports/results.sarif.json
      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: security-reports/results.sarif.json

  soos_scan:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    needs: semgrep_scan
    steps:
      - uses: actions/checkout@v4
      - name: Download SARIF artifact
        uses: actions/download-artifact@v4
        with:
          name: semgrep-results
          path: security-reports
      - name: Run SOOS SAST Scan
        uses: soos-io/soos-sast-github-action@v1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "${{ github.repository }}"
          source_code_path: security-reports
