name: SOOS SAST Scan

on:
  workflow_dispatch:

jobs:
  soos_sast_scan:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run SOOS SAST Scan
        uses: soos-io/soos-sast-github-action@v1
        with:
          clientId: ${{ secrets.SOOS_CLIENT_ID }}
          apiKey: ${{ secrets.SOOS_API_KEY }}
          projectName: "SCM Lite"

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "**/*.sarif.json"
