name: SOOS SAST Analysis

on: push

jobs:
  soos_sast_analysis:
    name: SOOS SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@v1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "scm"
