name: Semgrep SAST

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Still safe to use v3 for checkout

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # FIX: Updated to v4 to resolve the deprecation error
      - name: Upload Semgrep SARIF Artifact
        uses: actions/upload-artifact@v4 # <<<-- THE FIX IS HERE
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif
          retention-days: 7 

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3 # Still uses v3, which is the current stable version for CodeQL uploads
        with:
          sarif_file: semgrep.sarif
