name: Semgrep SAST

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # 👇 THIS NEW STEP SAVES THE FILE FOR DOWNLOAD
      - name: Upload Semgrep SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif
          retention-days: 7 # The file will be available for 7 days

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
