name: Semgrep SAST

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# To upload SARIF results to GitHub's Security tab, you need to grant the appropriate permissions.
permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep --sarif --output semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
